### ISSUE TITLE
Fortune System - Broken Compass Support

### ISSUE THREAD

**Issue by Naith123** [rollem-discord/rollem-discord#131]
The fortune system is pretty simple. It works via counting matching dice results. You roll a pool of d6s.

If you get;

2 of a kind - Basic Success
3 of a kind - Critical Success
4 of a kind - Extreme Success
5 of a kind - Impossible Success

You can have multiple successes. So if you rolled 6d6 and got 1, 1, 1, 3, 3, 6. 
You would have 1 basic success and 1 critical success.

**Comment by david-sharer** [comment]
![image](https://user-images.githubusercontent.com/26589071/167273199-a15804eb-f4d0-4f86-8073-a240b47a08eb.png)

Changed the grouping from ORE to max out at 5. It's in Rollem Next now.
