### ISSUE TITLE
One Roll Engine Support

### ISSUE THREAD

**Issue by Naith123** [rollem-discord/rollem-discord#132]
The One Roll Engine depends on matching dice values. They are then put into sets. The sets are written by the number of matching dice (width) and the size of the matching dice (height).

If someone rolled 10d10 and got 10, 8, 8, 6, 5, 4, 4, 2, 2, 2.

They would have the following sets. 2x8, 2x4, 3x2. 
Since the width and the height info is important, all the sets need to be displayed as the user can then select the one they want to use.

See here for a slightly fuller explanation - https://en.wikipedia.org/wiki/One-Roll_Engine

**Comment by david-sharer** [comment]
Grouping is live in Rollem Next now. Invite with this link. https://rollem.rocks/invite/next/
