### ISSUE TITLE
Resistance Toolkit (Spire/Heart) Support

### ISSUE THREAD

**Issue by Naith123** [rollem-discord/rollem-discord#194]
Notation for rolling risky and dangerous dice in Heart or Spire
![image](https://user-images.githubusercontent.com/24856132/211412372-33c97098-a96a-4435-884d-a6c16bfd3bb2.png)

See the attached image for a breakdown of how it works. Basically what is needed is notation for discarding a certain number of highest dice to select the remaining highest die in the pool

**Comment by david-sharer** [comment]
I think this is achievable with `10d10dh1` and `10d10dh2` (for "drop highest 1/2") but if you want me to make a more sensible shorthand notation specifically for Spire/Heart, we've done that for a few systems

**Comment by Naith123** [comment]
Nah the dh notation works great, don't think there is a need for anything more. Not sure why I didn't see it on the rollem docs when I looked before I asked on discord.
