### ISSUE TITLE
spoilered roll results

### ISSUE THREAD

**Issue by kjhsdgf** [rollem-discord/rollem-discord#200]
more of a request than an issue. currently, i don't think there is a way to have rollem display results wrapped in the spoiler tag (`||`). would be nice to add a feature that allows rollem to read spoilered input to indicate that the output should also be spoilered. For example,

||2d6 label||

'label',  ||` 10 `||  ⟵ ||[6, 4]|| 2d6

Preferably, only the random numbers would be wrapped in the spoiler tag, but

||'label', ` 10 ` ⟵ [6, 4] 2d6||

would be fine by me!

**Comment by david-sharer** [comment]
Resolved by #227
