### ISSUE TITLE
Syntax to Spoiler results

### ISSUE THREAD

**Issue by david-sharer** [rollem-discord/rollem-discord#225]
Add a syntax for providing bot results in a spoiler tag.

Syntax could be something like `s#3d6`, in the same vein as `6#3d6` for bulk-rolling.

This seems achievable to add in Syntax v1, since it should be easy to add outside of the usual roll parsing.

Sources:
- https://discord.com/channels/435304187442757634/1187263241718603786/1274096370831327242
- https://discord.com/channels/435304187442757634/1187263241718603786/1274106080917454858

**Comment by david-sharer** [comment]
related https://github.com/rollem-discord/rollem-discord/issues/200

**Comment by Nichlas-Schmidt** [comment]
https://github.com/rollem-discord/rollem-discord/pull/227

pull request here
