### ISSUE TITLE
T&T TARO error

### ISSUE THREAD

**Issue by dylanlester-librem** [rollem-discord/rollem-discord#226]
When I roll a taro roll and get matching dice it is meant to roll the dice pool again and add that to the result recursively till it stops getting matching dice.

Currently it rolls one additional die of the type used and adds it to the result until you get to the result recursively till a different result comes up on the die.

So it's meant to be 3d6taro resulting in 555 will then roll 3d6 again and add it's result to it after checking to make sure it's not a triplet then breaking the loop if it is not.

**Comment by david-sharer** [comment]
Yep that seems wrong. https://frank-mitchell.com/posts/tnt-nonreview/#:~:text=Players%20typically%20roll%203d6%20for,so%20on%2C%20and%20so%20on.

I assume this is meant to behave similarly for DARO configuration?
(`2d6daro` => [2+2] + DARO **2d6** => [2+2] + [3+3] + DARO **2d6** => [2+2] + [3+3] + [5+1])

And similar behavior for `4d6aro` and `5d6aro` and so forth? (all match = reroll entire input and sum?)

> Code chain (to save myself some hunting later):
> 1. Collect tag https://github.com/rollem-discord/rollem-discord/blob/204622329a5dfe1022284be97be6344649727bb1/packages/language/src/rollem-language-1/rollem.pegjs#L182
> 2. Configure roller https://github.com/rollem-discord/rollem-discord/blob/204622329a5dfe1022284be97be6344649727bb1/packages/language/src/rollem-language-1/rollem.pegjs#L178
> 3. Call roller https://github.com/rollem-discord/rollem-discord/blob/204622329a5dfe1022284be97be6344649727bb1/packages/language/src/rollem-language-1/rollem.pegjs#L163
> 4. Roller Entrypoint https://github.com/rollem-discord/rollem-discord/blob/204622329a5dfe1022284be97be6344649727bb1/packages/language/src/rollem-language-1/rollem-header.ts#L116
> 5. DARO/TARO/ARO loop https://github.com/rollem-discord/rollem-discord/blob/204622329a5dfe1022284be97be6344649727bb1/packages/language/src/rollem-language-1/rollem-header.ts#L136-L144

**Comment by dylanlester-librem** [comment]
Yes exactly correct the recursion would continue until the newly rolled and added dice pool do not match. Then that would break it out of the loop.
