### ISSUE TITLE
New Feature Request: Support for Tunnels and Trolls DARO/TARO

### ISSUE THREAD

**Issue by sirkerry** [rollem-discord/rollem-discord#29]
A feature to consider:
The game system Tunnels and Trolls has a thing similar to exploding dice, but slightly different. It's doubles and triples of the same value rolled get added and rolled over.

If possible, would be a nice feature to add.

**Comment by david-sharer** [comment]
So if you roll 5d6 and get 3 3 3 5 1, the 3s become 9 and all 3 dice get rerolled? If it happens again do you keep rolling?

**Comment by sirkerry** [comment]
Sorry for my being a little unclear there.  This only applies to 2d6 and 3d6 rolls.  So only doubles on 2d6 (i.e. both dice match), and only triples on 3d6 (i.e. all three dice match).  T&T uses the 3d6 TARO roll for attribute generation and the 2d6 DARO is used for what is referred to as Saving Rolls (but are actually ability checks).  The DARO (Doubles And Roll Over) and (Triples And Roll Over) keep getting rerolled and added until the condition doesn't happen again.

**Comment by david-sharer** [comment]
Ok that makes sense. Is there a standard notation for this in the system already?

**Comment by sirkerry** [comment]
David, sorry I don't understand the question?  Is there a standard notation in the Tunnels & Trolls system for this?  Not really, when talking about these types of rolls we generally just refer to them as ARO or DARO/TARO rolls.

**Comment by david-sharer** [comment]
Somehow didn't see this until now.

OK. So something like this would be a fine syntax?
```
2d6aro
3d6aro
```

I'm in the process of setting up a database so being able to set this as a thing for an entire channel/server may also be a thing later, if that's actually something useful.

**Comment by sirkerry** [comment]
yes that syntax would be fine

**Comment by david-sharer** [comment]
This is now live on the beta bot. Primary bot next week. Invite it to servers you own with this link https://rollem.rocks/invite-beta/
