### ISSUE TITLE
Arbitrary Exploding dice Trigger

### ISSUE THREAD

**Issue by Blaxe97** [rollem-discord/rollem-discord#31]
Instead of just `1d6!` let us use `1d6!4` to make the dice "explode" if the result is equal or greater than 4

**Comment by david-sharer** [comment]
This is from the Roll20 dice reference. What do you think of that?

https://wiki.roll20.net/Dice_Reference#Exploding_Dice
> You can also define the exploding point for the dice using the greater-than and less-than symbols. For example, /roll 3d6!>4 would explode on any dice greater-than or equal-to 4. /roll 3d6!3 would explode only if a 3 is rolled. 

> A common Shadowrun roll would be exploding dice compared to a target number, for example /roll {5d6!!}>8 (notice the use of the brackets to show that we don't mean "explode on anything greater than 8", but rather "explode on 6's compounding, then compare to 8 for successes). Even though the target number (8) is higher than the possible roll from a single die, with the compounding exploding rolls a single roll can be infinitely high!

**Comment by Blaxe97** [comment]
Tested it in the current bot, aplying the > symbol made it check for the valio of the dice as a boolean if Failure or Success... so that would be conflicting, wouldn't?

**Comment by david-sharer** [comment]
Correct.

I think to do this I would make a second "mode" to the dice parser that you could opt into, which would more closely match the roll20 features and syntax. Eventually this would become the default mode.

I've been meaning to start on it for a while.

---

Or...

An alternative to support both at the same time would be to introduce the above "mode" with a "containing" syntax, so we can tell which meaning of the syntax we should be considering Such as by enclosing part of the roll in the curly braces {}. That's compatible with both Rollem's style and the Roll20 style.

Examples:
- Using both: `4d6 + {3d6!>4} > 4`
- Same roll using just Roll20-style: `{4d6 + {3d6!>4} > 4}`
- It's wouldn't be possible using just Rollem-style

---

Or...

I could add it both ways - as you suggest above with `3d6!4` for Rollem-style, and start work on the `{roll20 style}`. It's not much more work.

**Comment by david-sharer** [comment]
The `3d6!4` style is now live on Rollem Beta. Here's an invite link. https://rollem.rocks/invite-beta/

It will go to Rollem Prod after about a week if there's no issues.
