### ISSUE TITLE
Rollem Down (2021-02-12)

### ISSUE THREAD

**Issue by bakergeek** [rollem-discord/rollem-discord#67]
In the middle our our game tonight rollem stopped responding. It was working fine for the first half of our session and then suddenly stopped and would not respond to anything.

**Comment by david-sharer** [comment]
There is a Discord API issue right now with Sharding, where it reports SHARDING_REQUIRED (and terminates the bot) even when you are sharding correctly.

This has impacted many larger bots. Discord knows about it and is working on a resolution. You can [join the support server](https://discord.gg/VhYX9u7) and follow #notifications to know when that is resolved (as I will be doing), and then I will restart the bot. I will send out another notification on the server (and reply to this issue) when the bot is back up.

Sorry everyone!

**Comment by david-sharer** [comment]
The bot is now at least partially up, but there is no official announcement. I am seeing a few rolls go through. I will continue to periodically restart the bot until it is stable again.

**Comment by david-sharer** [comment]
The bot appears to be fully up now on my end, though there is not yet an announcement from Discord. Others are reporting the same.

**Comment by david-sharer** [comment]
Discord has announced the rollout is complete.
