### ISSUE TITLE
& and r commands are not working

### ISSUE THREAD

**Issue by ShiroiOkami11** [rollem-discord/rollem-discord#88]
Your & and r math commands stopped working man hope you can get them running again pretty oon i use them a lot in my combats and non-combat stuff with my players

**Comment by david-sharer** [comment]
Hello! Thanks for the report. Looking into it now.

**Comment by david-sharer** [comment]
I think I have found the issue.

As a workaround until the fix goes out, it should be possible to ping rollem to perform the path like `@rollem 20+20`

**Comment by david-sharer** [comment]
This is now going out to shards 1-20 and 30 as a hotfix for the previous release.
Please let me know if anything else has gone wrong.
